version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: hes_timescaledb
    environment:
      - POSTGRES_USER=hes_user
      - POSTGRES_PASSWORD=hes_password
      - POSTGRES_DB=hes_db
    ports:
      - "5433:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hes_user -d hes_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  timescaledb_data:
    driver: local 